### ISSUE TITLE
panic: runtime error: invalid pointer

### ISSUE THREAD

**Issue by mh4nx7net** [m00qek/swaynag-battery#3]
is something went wrong ?
![grimshoot-slurp-2020-03-18-22-59-17](https://user-images.githubusercontent.com/33443311/76980723-22d52580-696c-11ea-9608-5eaafb6a5b9b.png)

**Comment by m00qek** [comment]
Hi, thanks for reporting :bowing_man: 
Seems like your uevent path is not ` /sys/class/power_supply/BAT0/uevent`, you will need to run `swaynag-battery` passing the correct one as an argument:

```bash
swaynag-battery --uevent /sys/class/power_supply/<your-battery>/uevent
```
